version: "3.8"

services:
  mysql:
    build: ./mysql
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./mysql/data:/var/lib/mysql
  phpmyadmin:
    image: arm64v8/phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
  php:
    build: .
    ports:
      - 80:80
    environment:
      DB_HOST: "mysql"
      DB_DATABASE: "db"
      DB_USERNAME: "user"
      DB_PASSWORD: "password"
    volumes:
      - ./src/slike:/var/www/html/slike
      - ./php.ini:/usr/local/etc/php/php.ini

volumes:
  uploads:
